### ISSUE TITLE
freeze.sh doesn't work

### ISSUE THREAD

**Issue by hao-fang** [Mini-Conf/Mini-Conf#19]
I got this error message when running `./freeze.sh` and no files are generated.
```
./env/lib/python3.7/site-packages/flask_frozen/__init__.py:199: MissingURLGeneratorWarning: Nothing frozen for endpoints send_static. Did you forget a URL generator?
  return set(page.url for page in self.freeze_yield())
```

**Comment by srush** [comment]
It should still work with that warning. Do you see a build/ directory? after running it?

**Comment by hao-fang** [comment]
oh sorry, I didn't notice the `build` folder last night.
(We may add a sentence in the README -- I can create a PR.)
