### ISSUE TITLE
Clean up CDN

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#25]
We get the javascript from several different CDNs would be nice to standardize.

**Comment by animesh-007** [comment]
> We get the javascript from several different CDNs would be nice to standardize.

Can you tell me exactly what I should do to resolve this issue

**Comment by ArpanSriv** [comment]
All the CDNs are already from jsdelivr. What do you mean by standardizing?

**Comment by srush** [comment]
I don't think that's true. There are a bunch in template/ like base.html that are from various different cdns.

**Comment by ArpanSriv** [comment]
Oh alright. I'll do it.
