### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#26]
Style and build checks.

**Comment by animesh-007** [comment]
Will it be okay if I used Travis Ci?

**Comment by hao-fang** [comment]
I see there is a #27 to use Travis CI.
FWIW: I had set up a Github Action for our ACL fork [here](https://github.com/acl-org/acl-2020-virtual-conference/pull/10).

**Comment by srush** [comment]
Is GitHub actions better? Just curious.

**Comment by hao-fang** [comment]
@srush I'm new to both. I only used CircleCI and AzurePipelines, but they all seem similar so probably fine.
Probably GitHub Action is slightly better b/c it is native to GitHub.
I can set up GitHub Action with my current permission, but only people with org-level permission can set up TravisCI.

With #27 we still need to configure TravisCI to monitor this repo. This requires the org admin to do it.

Probably I can to move https://github.com/acl-org/acl-2020-virtual-conference/pull/10 to this repo and enable Github Actions. and Are you okay with that?

**Comment by srush** [comment]
Sure, do whatever keeps us relatively in sync with ACL.
