### ISSUE TITLE
Only allow "squash and merge"

### ISSUE THREAD

**Issue by hao-fang** [Mini-Conf/Mini-Conf#28]
I notice that the master commit history contains intermediate commits for PRs. 
Probably good to always do "Squash and merge".

Can be done by in "Settings".
![Screen Shot 2020-05-22 at 11 14 40 PM](https://user-images.githubusercontent.com/9957482/82723213-0615e080-9c82-11ea-9215-03cef62351fa.png)

**Comment by srush** [comment]
Done.

I also made you an admin, feel free to take some ownership. In general our goal to keep things pretty simple for non-contribs / forkers so take that into account. Everything else is great though.

**Comment by hao-fang** [comment]
Thanks! I just added a `master` branch protection rule [here](https://github.com/Mini-Conf/Mini-Conf/settings/branch_protection_rules/16105469) which requires at 1 approval for merging PRs to master.
And I enabled "Include administrators" so that admins will not accidentally push directly to master. This may make it easier to revert changes.
