### ISSUE TITLE
Integrate an open-source chat system.

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#29]
We would like to have a default chat system built in with a script that creates chat rooms for each paper. 

One idea would be to use rocket.chat, but maybe there is something with a better license.

**Comment by animesh-007** [comment]
@hao-fang I want to implement 1st task but I am unable to find Rocketchat implementation on the ICLR website.
Can you help me so that I can start working on it?

**Comment by srush** [comment]
All we did was add this code to our poster.html pages: 

 <center>
        <iframe frameborder="0" src="https://iclr.rocket.chat/channel/{{openreview.content.chat}}?layout=embedded" height="700px" width="100%" ></iframe>
</center>

**Comment by srush** [comment]
In order to create rooms we read the sitedata/ directories and used it to create rooms:

``
from rocketchat_API.rocketchat import RocketChat
with sessions.Session() as session:
    rocket = RocketChat({USER},  {PASSWORD}, server_url={SERVER}, session=session)

    workshops = yaml.load(open("../sitedata/socials.yml"))
    for i, s in enumerate(workshops["socials"]):
        name = ("social_" + s["id"])
        # rocket.channels_create("social_" + s["id"])
        topic = s["name"] + "  Orgnanizers: " + s["organizers"] 
        id = rocket.channels_info(channel = name).json()["channel"]["_id"]
        print(rocket.channels_set_topic(id, topic).json())
```

**Comment by hao-fang** [comment]
@srush Do you want to add RocketChat integration in the main Mini-Conf repo?
ACL has decided to follow ICLR to use RocketChat, so we can integrate it in our fork if you want to support other chat system with a better license.

**Comment by srush** [comment]
I was mistaken, it seems like rocket.chat has a good license. 

I would be for just building it into the main repo if that helps you guys. I can share all my scripts.

**Comment by hao-fang** [comment]
That would be great! Thanks @srush!
@animesh-007 Do you think you get enough information to start?

**Comment by animesh-007** [comment]
Yes! Thanks for all the information I will start working on it.
@srush It will be great that you will be sharing your scripts.
Just let me know when you share it so that I can start working.

**Comment by srush** [comment]
I mean mostly we just did that above ^ for papers, workshops, speakers, etc. But I will put together a test example server.
