### ISSUE TITLE
Deploy inline. 

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#31]
`make deploy` Configuration to deploy directly to a gh-pages in the same repo.

**Comment by ArpanSriv** [comment]
I'll do this!

**Comment by srush** [comment]
great, you can just fork it and set up gh-pages for your fork.

**Comment by ArpanSriv** [comment]
I'm getting the following on `make freeze`. Is this normal?
```❯ make freeze
python3 main.py sitedata/ --build
Data Successfully Loaded
/Users/sriv_arpan/opt/anaconda3/lib/python3.7/site-packages/flask_frozen/__init__.py:199: MissingURLGeneratorWarning: Nothing frozen for endpoints send_static. Did you forget a URL generator?
  return set(page.url for page in self.freeze_yield())
```

**Comment by hao-fang** [comment]
@ArpanSriv it's fine (see #19). You should see a `build/` folder after running this command

**Comment by ArpanSriv** [comment]
Yes I do see the build folder! Thanks!

**Comment by ArpanSriv** [comment]
So I'm trying to deploy the `build` folder to gh-pages in the repo, using the `git subtree push` but that would need me to add the `build` folder to the vcs. Is this right?
