### ISSUE TITLE
Document AWS login / auth strategy

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#32]
Not sure how to do this statically but it seems worth trying.

**Comment by hao-fang** [comment]
I'll make a document once I figured out everything this week.

**Comment by hao-fang** [comment]
I followed [this tutorial](https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-using-cookies-protect-your-amazon-cloudfront-content-from-being-downloaded-by-unauthenticated-users/) and it is quite easy to set up.

When accessing the website, the login interface looks like this
![image](https://user-images.githubusercontent.com/9957482/83993678-f5fc3300-a908-11ea-98ba-30adaeebfd53.png)

And the admin can manage the user pool via [Amazon Cognito](https://aws.amazon.com/cognito/).

The tutorial is pretty clear and straightforward, so I didn't write a new one.

**Comment by srush** [comment]
Hi Hao,

I started looking at using Auth0 for auth and it seems pretty nice to configure. aws scares me a bit, that tutorial was intense. I think I am going to try setting that up as the default example mode. I'll let you know how it goes.

**Comment by hao-fang** [comment]
Yeah, it indeed involves many components, mostly to deal with scalability.
The tutorial is long, but the actual action is just click [this link](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge) which will create all necessary AWS resources. Then the remaining step is just to 1) upload files to S3 bucket, and 2) add users to the User Pool in the Amazon Cognito.

But I agree that if Auth0 is easy to configure then it is better to use it as the default. The AWS setup is an independent solution that does not need to be tied with the repo. Probably we can just add a sentence to point this AWS solution as an alternative when documenting the auth strategy.

**Comment by srush** [comment]
sounds good, I will add a link. 

What I potentially like about auth0 is that is has a nice solution to the chat sign on as well. Is that something you need as well?

**Comment by hao-fang** [comment]
Yes, that would be useful for us as well!
