### ISSUE TITLE
Automatic keyword generation

### ISSUE THREAD

**Issue by srush** [Mini-Conf/Mini-Conf#34]
Some clever way of generating keywords.

**Comment by anaerobeth** [comment]
Interested in helping with this feature.

**Comment by srush** [comment]
Great. I don't actually have a great idea of how to do it. @HendrikStrobelt suggested using noun phrases. But would also be neat if there were papers with interesting approaches.

**Comment by hao-fang** [comment]
Extracting NP seems to be a good start, but I feel many keywords might not be a noun phrase in the abstract, e.g., deep learning, nlp. Also NP might be too noisy, e.g., “state-of-the-art results”.

FWIW: This paper and the data used in it might be useful. 
http://nlp.cs.washington.edu/sciIE/
And here is a follow-up work https://github.com/dwadden/dygiepp

**Comment by anaerobeth** [comment]
I've used textacy in building dashboards with top keywords and key phrases from various text documents: https://chartbeat-labs.github.io/textacy/build/html/api_reference/information_extraction.html .  I compare the results of different approaches and see what suits our need.s

**Comment by srush** [comment]
@anaerobeth sounds great!

**Comment by anaerobeth** [comment]
Apologies for not posting any progress on this as the last two weeks have been challenging. Looking to spend some time on this next week.

**Comment by anaerobeth** [comment]
First pass at comparing algorithms for automatic keyword extraction: https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/scripts/generate_keywords.py 

Please take a look at the sample results below if this effort is in the right direction. The final implementation can draw from a curated list of keywords identified by multiple algorithms. Thanks!

https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_scake.csv
https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_yake.csv
https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_textrank.csv

**Comment by hao-fang** [comment]
@anaerobeth I briefly looked through the generated files. It seems that the keywords are pretty noisy. A few examples below.
* TextRank:  "current time step", "few time step", "general neural network weight compression approach"
* Yake: "network", "human"
* Scake: "shot text classification", "meta"

You may need to use some heuristics. Alternatively, you may think about doing some 
intersection among three algorithms to get higher precision.

BTW, have you tried https://github.com/dwadden/dygiepp? I talked with the author and she thinks their model is likely to work on scientific papers.

**Comment by anaerobeth** [comment]
@hao-fang Here are the results of limiting the phrases to those found by more than one algorithm:
- phrases that appear in the top 10 results of at least 2 algorithms
  https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_filtered.csv
- common phrases in the top 20 results of all three algorithms:
  https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_intersection.csv
- common phrases in top 50 results of all three algorithms:
  https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_intersection_top50.csv

One shortcoming seems to be how hyphenated words are handled; for example, "few-shot classification algorithm" is extracted as "shot classification algorithm". 

I will spend some time this week adapting DyGIE++ to this dataset and comparing the results.

**Comment by hao-fang** [comment]
@anaerobeth Cool thanks! I'm also curious about how DyGIE++ works on this task. Look forward to the results!

**Comment by anaerobeth** [comment]
The maintainer of DyGIE++ will be writing some documentation to help up get started with this task: https://github.com/dwadden/dygiepp/issues/22 .

**Comment by anaerobeth** [comment]
I've confirmed that  new DyGIE++ preprocessing script works on the dataset of miniconf abstracts.  I am now running the model and will post the results in a couple of days.

**Comment by anaerobeth** [comment]
Link to generated keywords using DyGIE++ (based on NER predictions from the pretrained SciERC model): https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/sitedata/generated_keywords_dygie_full_model.csv

I'll spend some time adding documentation on how to use DyGIE++ on the dataset and cleaning up script
https://github.com/anaerobeth/Mini-Conf/blob/34-automatic-keyword-generation/scripts/generate_keywords_dygiepp.py

**Comment by hao-fang** [comment]
Looks less noisy than the previous method. But I'll defer to @srush to see what the next should be.
(For ACL2020, we may not include this feature given the current time constraint.)
