### ISSUE TITLE
Set up Github Issue Template

### ISSUE THREAD

**Issue by hao-fang** [Mini-Conf/Mini-Conf#37]
It may be good to have separate issues for feature request & bug report, similar to [here](https://github.com/codalab/codalab-worksheets/issues/new/choose).

We can probably adapt their template [here](https://github.com/codalab/codalab-worksheets/tree/master/.github/ISSUE_TEMPLATE).

**Comment by srush** [comment]
Let's wait to see if we actually get a lot of issues...

**Comment by hao-fang** [comment]
Close for now. We can re-open if needed.
