### ISSUE TITLE
Replace https://fonts.googleapis.com

### ISSUE THREAD

**Issue by hao-fang** [Mini-Conf/Mini-Conf#59]
It seems that we are using some css files from https://fonts.googleapis.com.
https://github.com/Mini-Conf/Mini-Conf/blob/master/templates/base.html#L45-L53
These may not work in some areas like mainland China.
Is there an alternative for these files?

**Comment by srush** [comment]
great question. my recs say http://libs.useso.com/ but it doesn't seem to work?

**Comment by hao-fang** [comment]
http://libs.useso.com/  doesn't work for me either.
Sorry, I don't have much experience on this so I don't know what the best solution is.

**Comment by srush** [comment]
https://github.com/Mini-Conf/Mini-Conf/pull/64
