### ISSUE TITLE
Integration with Jitsi

### ISSUE THREAD

**Issue by yarikoptic** [Mini-Conf/Mini-Conf#78]
Wow, if I only knew you existed 2 weeks ago.  During OHBM conference we had to quickly establish an "alternative" poster session to the one provided by a commercial solution.  You can see it in action at https://datalad-datasets.github.io/ohbm2020-posters/ . The savior was free https://meet.jit.si which allowed to "mint" rooms per each poster. Later EtherPad was bolted on to provide persistent notes etc.  May be it would give ideas ;)

Cheers and thank you for the GREAT WORK!

**Comment by srush** [comment]
Thanks! I'll check it out.
