### ISSUE TITLE
SlidesLive not loading for ICML, but works correctly for ACL.

### ISSUE THREAD

**Issue by SamujjwalSam** [Mini-Conf/Mini-Conf#87]
SlidesLive for individual papers is not loading for ICML for some reason. However, It works fine at ACL virtual website. I opened both from the same browser (Firefox), same machine (Ubuntu), even same window, etc. 

Please find the screenshots for both below:

> ## SlidesLive (ICML):
> ![SlidesLive_ICML](https://user-images.githubusercontent.com/3850813/87219533-a7174280-c379-11ea-84ad-63dbcd34dff1.png)
> [Here's the link the screenshot shows](https://slideslive.com/3rd-party-cookies)
> 
> 
> ## SlidesLive (ACL):
> ![SlidesLive_ACL](https://user-images.githubusercontent.com/3850813/87219535-aa123300-c379-11ea-98ce-220662b32b77.png)

**Is there some configuration difference between the two?**

**Comment by srush** [comment]
Is your browser purposefully blocking cookies? I wonder if the two conferences configured SlidesLive differently.

**Comment by SamujjwalSam** [comment]
Not very sure but could be a reason. Failed on Firefox and Brave, however working on Opera with VPN.

**Comment by hao-fang** [comment]
We had some initial issues with playing SlidesLive in Safari, and it turns out that SlidesLive needs to change some settings in Viemo. Maybe check with SlidesLive about this.
