### ISSUE TITLE
MCSDMS: Mini-Conf /sitedata  management systems/setups

### ISSUE THREAD

**Issue by yarikoptic** [Mini-Conf/Mini-Conf#97]
I wonder what setups/systems people use/recommend to manage/populate sitedata and related content?  E.g. for a conference with a few 1,000 of participants who need to upload their posters (pdfs) and pre-recorded talks -- how could it be streamlined.

**Comment by srush** [comment]
It's a good question. Mini-Conf doesn't provide any support for this directly. For ICLR we used OpenReview and SlidesLive. Other conferences have used SoftConf and YouTube. It would be nice to hear what others are trying here.
